name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deployment:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy to firebase
      run: sudo xcode-select -switch /Applications/Xcode_12.app
   # - name: Build 
    #  run: xcodebuild -project "MultiplicationPractice.xcodeproj" -scheme "MultiplicationPractice" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
   # - name: Run SwiftLint
    #  run: sudo xcode-select -switch /Applications/Xcode_12.app
   # - name: Test
    #  run: sudo xcode-select -switch /Applications/Xcode_12.app
