name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Build 
      run: xcodebuild -project "MultiplicationPractice.xcodeproj" -scheme "MultiplicationPractice" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: swift test -v
