name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.5.app
    - name: Build
      run: 
          xcodebuild clean test -project "MultiplicationPractice.xcproj" -scheme "MultiplicationPractice" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Run tests
      run: swift test -v
